name: CI Workflow
on: [push]
jobs: 
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: print hello world
        run: echo "Hello world"
  greeting:
    runs-on: ubuntu-latest
    steps: 
      - name: say good morning
        run: echo "good morning"       